### ISSUE TITLE
Current state?

### ISSUE THREAD

**Issue by paviro** [StraToN/godot_pointandclickadv#2]
Hi there,
Is there any progress on your project?

Cheers,
Paul

**Comment by StraToN** [comment]
Hi @paviro 
For the moment I am busy with my DialogTree tools side-project (https://github.com/StraToN/godot-dialogtreetools) which is closely related to this Point&Click demo. I need this addon to work in order to continue the demo. Many people are interested with it too, so this one has my time for now.

Once it's done, here's what's next with this demo project:
- NPC dialogs
- Items (pick & use) and Inventory
- After that, I'll add some rooms and allow room travels.

Preview: after all this is done, I'll add another example... in 3D ;)
